Install properly

diff --git a/miriway-background b/miriway-background
--- a/miriway-background
+++ b/miriway-background
@@ -1,2 +1,16 @@
 #!/bin/sh -e
-exec swaybg -i /usr/share/backgrounds/warty-final-ubuntu.png
+
+if ! command -v swaybg > /dev/null; then
+  echo "WARNING: swaybg not found"
+  exit 1
+fi
+
+# Try copying GNOME background
+if command -v gsettings > /dev/null; then
+  background=$(gsettings get org.gnome.desktop.background picture-uri | sed -Ee "s|[^:]*://(.*\.png)'$|\1|")
+  if [ ! -e "${background}" ]; then
+    unset background
+  fi
+fi
+
+exec swaybg -i "${background:-/usr/share/backgrounds/warty-final-ubuntu.png}"
